### ISSUE TITLE
Update user settings to be parity with 0.19

### ISSUE THREAD

**Issue by jgrim** [sublinks/sublinks-api#122]
The list of user settings on Lemmy are:

1. show_nsfw?: boolean;
2. blur_nsfw?: boolean;
3. auto_expand?: boolean;
4. show_scores?: boolean;
5. theme?: string;
6. default_sort_type?: SortType;
7. default_listing_type?: ListingType;
8. interface_language?: string;
9. avatar?: string;
10. banner?: string;
11. display_name?: string;
12. email?: string;
13. bio?: string;
14. matrix_user_id?: string;
15. show_avatars?: boolean;
16. send_notifications_to_email?: boolean;
17. bot_account?: boolean;
18. show_bot_accounts?: boolean;
19. show_read_posts?: boolean;
20. discussion_languages?: Array<LanguageId>;
21. open_links_in_new_tab?: boolean;
22. infinite_scroll_enabled?: boolean;
23. post_listing_mode?: PostListingMode;
24. enable_keyboard_navigation?: boolean;
25. enable_animated_images?: boolean;
26. collapse_bot_comments?: boolean;

**Comment by Pdzly** [comment]
@jgrim i will have a look into this.

**Comment by Pdzly** [comment]
show_nsfw?: boolean; E
    blur_nsfw?: boolean; M
    auto_expand?: boolean;  M
    show_scores?: boolean; E
    theme?: string; E
    default_sort_type?: SortType; E
    default_listing_type?: ListingType; E
    interface_language?: string; E
    avatar?: string; E
    banner?: string; E
    display_name?: string; E
    email?: string; E
    bio?: string; E
    matrix_user_id?: string; E
    show_avatars?: boolean; E
    send_notifications_to_email?: boolean;E
    bot_account?: boolean; E
    show_bot_accounts?: boolean; E
    show_read_posts?: boolean; E
    discussion_languages?: Array; E
    open_links_in_new_tab?: boolean; E
    infinite_scroll_enabled?: boolean; M
    post_listing_mode?: PostListingMode; M
    enable_keyboard_navigation?: boolean; M
    enable_animated_images?: boolean; M
    collapse_bot_comments?: boolean; M
    
    E = Exists
    M = Missing
