### ISSUE TITLE
Check for need of new type LoginToken from Lemmy 0.19

### ISSUE THREAD

**Issue by jgrim** [sublinks/sublinks-api#124]
Check if the new type is needed in any response or request.

https://github.com/LemmyNet/lemmy-js-client/compare/0.18.0-rc.1...0.19.0#diff-e7605be6163b260e3d9381391d26c5b0263995192d3e920e62889a76f0e3bcb0

**Comment by Pdzly** [comment]
So far i know the type is "still" a jwt BUT instead adding it to the header ( on some GET requests ) You have to have it in the cookies OR headers of the request ( as a BEARER )

@jgrim
