### ISSUE TITLE
Add support for RabbitMQ

### ISSUE THREAD

**Issue by lazyguru** [sublinks/sublinks-api#139]
- Add a producer and connect to topic for sending to Federation
- Add a consumer and connect to topic for receiving from Federation

**Comment by lazyguru** [comment]
Topic names are maybe still TBD, but for now I am labeling them based on destination. So "federation" is for any message going to the Federation service and "backend" is for any message going to the Java backend (eg, the service in this repo)

**Comment by lazyguru** [comment]
Feel free to reference https://github.com/sublinks/sublinks-federation/pull/28 for the docker-compose.yaml on running RabbitMQ

**Comment by devanbenz** [comment]
Branch was merged in closing this issue: 5744955af07a743204a09427abb24a5a67a0dca4
