### ISSUE TITLE
Support for magnet links

### ISSUE THREAD

**Issue by brandrich** [sublinks/sublinks-api#167]
`UrlUtil.java`'s `checkUrlProtocol()` method supports magnet links. [See this line of code](https://github.com/sublinks/sublinks-api/blob/5f25fd42fc488eda9dd9f5169a185e6c16791996/src/main/java/com/sublinks/sublinksapi/utils/UrlUtil.java#L83). However, out of the box Java only has support for http, https, file, and jar protocols ([see the Java docs](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URL.html)). So when attempting to check the protocol on a magnet link the URL constructor throws a `MalformedURLException`. A protocol handler for magnet links will need to be created.

**Comment by CheatCodeSam** [comment]
I'm thinking of doing this with just a regex.

**Comment by brandrich** [comment]
As in using a regex to pull the protocol from a given url?

**Comment by CheatCodeSam** [comment]
Yeah, but it would also require reworking [this function](https://github.com/sublinks/sublinks-api/blob/5f25fd42fc488eda9dd9f5169a185e6c16791996/src/main/java/com/sublinks/sublinksapi/utils/UrlUtil.java#L31), but I still think that might be easier than having to integrate magnet links into java.net.URL.

**Comment by brandrich** [comment]
I think a regex would work alright, but writing a small custom handler might be less work than perhaps expected. I did find a decent guide for creating a custom handler: https://www.oreilly.com/library/view/learning-java/1565927184/apas02.html.

I think just extending the URLStreamHandler class and overriding the `parseUrl` method would be enough for our uses. At least within the scope of UrlUtil.java. You'd also have to dummy `openConnection` but I don't see that being a big deal since I don't think it would ever be used.

**Comment by brandrich** [comment]
After fixing this bug enable this `givenValidMagnetUrl_whenCheckUrlProtocol_thenDoNothing()` test in UrlUtilUnitTests.java. The test should now pass.
