### ISSUE TITLE
Non-alphanumeric characters are not removed when converting a string to a slug

### ISSUE THREAD

**Issue by brandrich** [sublinks/sublinks-api#173]
stringToSlug() in SlugUtil.java is using String.replace() to [replace non-alphanumeric characters with spaces here](https://github.com/sublinks/sublinks-api/blob/7be49ca5d6853779eead4360b123364befe1191b/src/main/java/com/sublinks/sublinksapi/utils/SlugUtil.java#L23). String.replace()'s first parameter is expected to be a character sequence, but is being passed a regex here. Meaning that String.replace() is not actually replacing any non-alphanumeric characters. This call to String.replace() should be swapped out for String.replaceAll() which works with a regex.

**Comment by brandrich** [comment]
After making this change enable the `givenStringWithNonAlphaNumericCharacters_whenStringToSlug_thenReturnStringAsSlug()` test in SlugUtilUnitTest.java. The test should now pass.

**Comment by tuckerthomas** [comment]
Hey @jgrim looks like this might have already been handled by #211 ? I checked main for both changes and they seem to be there. Any info?

**Comment by jgrim** [comment]
@tuckerthomas yes, looks fixed. Thanks!
