### ISSUE TITLE
Person Mention API

### ISSUE THREAD

**Issue by jgrim** [sublinks/sublinks-api#2]

**Comment by 8ullyMaguire** [comment]
@jgrim there's something weird going on with this feature in https://discuss.online

![Screenshot from 2024-03-02 22-00-28](https://github.com/sublinks/sublinks-api/assets/126260333/99c76ba4-c756-4502-9f99-8fbd3fa1658c)

**Comment by lazyguru** [comment]
@8ullyMaguire discuss.online is not running Sublinks (yet).  It's still on Lemmy
