### ISSUE TITLE
Audit activitypub entity responses

### ISSUE THREAD

**Issue by jgrim** [sublinks/sublinks-api#24]
Some responses do not provide the activity pub URL or actor ID. The federation service needs them.

Audit the responses and ensure all responses will have complete data, including federation fields.

**Comment by devanbenz** [comment]
@jgrim just checking - I see a Community model with https://github.com/sublinks/sublinks-api/blob/f3f85e551389495ba9d968d8d02b32cf806baeb3/src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/community/models/Community.java#L17 & https://github.com/sublinks/sublinks-api/blob/f3f85e551389495ba9d968d8d02b32cf806baeb3/src/main/java/com/sublinks/sublinksapi/api/lemmy/v3/community/models/Community.java#L22

These are the expected fields that need to exist in response entities within the lemmy api packages?

**Comment by jgrim** [comment]
@devanbenz yes! Thanks a lot

**Comment by devanbenz** [comment]
> [@devanbenz](https://github.com/devanbenz) yes! Thanks a lot

Do we need to add an `actor_id` or `actor` to all the entities as well? I was reading through the apub documentation today and saw that apub messages need to have an actor, inbox, and id.

**Comment by lazyguru** [comment]
> > [@devanbenz](https://github.com/devanbenz) yes! Thanks a lot
> 
> Do we need to add an `actor_id` or `actor` to all the entities as well?

Only if we need it for sending to federation service. Backend should ideally not need to know any of the details about federation.

**Comment by devanbenz** [comment]
> > > [@devanbenz](https://github.com/devanbenz) yes! Thanks a lot
> > 
> > 
> > Do we need to add an `actor_id` or `actor` to all the entities as well?
> 
> Only if we need it for sending to federation service. Backend should ideally not need to know any of the details about federation.

Sounds good - so basically, comments, posts, user profiles? Would this info be good to use as a reference to what should be sent to federation? https://github.com/sublinks/sublinks-federation/tree/main/api/json-ld/lemmy

**Comment by lazyguru** [comment]
That works for what we need to output in the federation service, but we don't necessarily need them from the backend like that. Some of it we can infer/generate ourselves from the data (eg, we don't need an actor field that is in URL format, we just need the username somewhere and we'll generate the proper actor_id field)

**Comment by devanbenz** [comment]
@lazyguru do you think I can close this issue since it's not relevant?

**Comment by lazyguru** [comment]
No, I think this issue's purpose can be different than originally intended. We should remove any URL/model handling in the Java code for things that we intend to handle in the federation service. This should save them from having dead code here. You can assign this to me and I'll take a look through as I've gotten fairly familiar on what is and isn't federation related.

**Comment by devanbenz** [comment]
Great that sounds good to me. Would love to pair up with you on it so I can get a better understanding of what should be federation and not federation related :D
