### ISSUE TITLE
Purge Comment

### ISSUE THREAD

**Issue by Pdzly** [sublinks/sublinks-api#258]

**Comment by devanbenz** [comment]
@Pdzly could I have a bit more information for this ticket?

**Comment by lazyguru** [comment]
@devanbenz normally if a user (or 
mod) deletes a comment, it just flags the comment as deleted in the database and then the frontend displays a static “comment deleted” message. However, the content of the comment is still in the database. Purge deletes the record from the database. On Lemmy, this is a instance admin only function.
