### ISSUE TITLE
Fix slur filter replace

### ISSUE THREAD

**Issue by jgrim** [sublinks/sublinks-api#262]
When censoring text the word getting censored ends up being replaced with a number of '*' equal to the length of the slur regex. In this case the word being censored has a length of 5, but after censoring is replaced by 11 '*'.

I believe that block & report types should be on post POST|PUT while replace should happen on GET to account for changes to the slur filter regex. cc: @Pdzly

**Comment by Pdzly** [comment]
Wdym on response? During request of the post/comment?
