### ISSUE TITLE
Automatic purging of removed posts every set interval

### ISSUE THREAD

**Issue by Pdzly** [sublinks/sublinks-api#332]

**Comment by Pdzly** [comment]
I would not say it should remove every 30 minutes every removed post, i would say  if its 30 minutes ago removed it should "purge" it.

**Comment by gaviscapes** [comment]
I think having a way a to do so on a changeable interval would be helpful. Like every 30 to 90 days or so.

**Comment by jgrim** [comment]
I don't think that every removed posts needs to be purged. Comment section might still be helpful.

**Comment by gaviscapes** [comment]
> I don't think that every removed posts needs to be purged. Comment section might still be helpful.

This idea was coming from a place of thinking it might still function how lemmy does, but I assume it would be moot if the frontend hid removed posts for moderators and admins on a separate display anyway.

**Comment by Pdzly** [comment]
And for gdpr sake, and moderation, otherwise a malicious use will just delete undelete it forever.

As purging/permanent editing of comments / posts. So that no user created data is left really.

**Comment by Pdzly** [comment]
@gaviscapes this will break mod logs. I could see this as like a new flag "Hidden". Where it hides it in the list for everyone. 

But direct access still shows you that.
