### ISSUE TITLE
The updatedAt property of SlurFilter is immutable

### ISSUE THREAD

**Issue by lazyguru** [sublinks/sublinks-api#373]
Seeing this error in the logs:

```
HHH000502: The [updatedAt] property of the [com.sublinks.sublinksapi.slurfilter.entities.SlurFilter] entity was modified, but it won't be updated because the property is immutable.
```

**Comment by rohit-satya** [comment]
@lazyguru Please assign this issue to me

**Comment by rohit-satya** [comment]
@lazyguru Please review above PR

**Comment by Pdzly** [comment]
![grafik](https://github.com/sublinks/sublinks-api/assets/34943569/fce8609b-5e43-4fcd-88b5-1d74910f51d6)

After investigating it, this function in the SlurFIlterService is the source of this error. ( Used in the sitecontroller for updating and creating the sites slur filter )

I dont know WHY this code would ever edit the updatedAt attribute? but the error wont show up if i comment out the usage in the edit site endpoint.

**Comment by Pdzly** [comment]
Ahhh found out why. The @UpdatedTimestamp updates the attribute.

**Comment by Ashwinn11** [comment]
why updatable is false here? In SlurFilterService , we are updating regex attribute. Whenever a attribute is modified , the updatedAt should be updated right?

**Comment by lazyguru** [comment]
Because the ORM is allowed to update it, but the field itself should not be modifiable by code or user action

**Comment by Ashwinn11** [comment]
Removing @UpdateTimeStamp for UpdatedAt attribute should work
