### ISSUE TITLE
[Login] Usernames are case senstivie when logging in

### ISSUE THREAD

**Issue by jgrim** [sublinks/sublinks-api#379]
When logging into Sublinks the username is case sensitive. Usernames should not be case sensitive.

Example: Logging in to the user devAdmin will fail if you type the username devadmin.

**Comment by Ashwinn11** [comment]
I would like to work on this issue. May I get assigned

**Comment by Ashwinn11** [comment]
Done. I have just updated the person repository to perform case-insensitive query for name. Waiting for PR review
