### ISSUE TITLE
Add unit tests to Utils & Language

### ISSUE THREAD

**Issue by Pdzly** [sublinks/sublinks-api#41]
Choose a unit testing framework, and implement the CI/CD. Add unit tests to the current codebase. Update the contribution document with anything necessary regarding adding unit tests to future PRs.

**Comment by jgrim** [comment]
Consider using https://cucumber.io/docs/installation/java/ for BDD testing.

**Comment by brandrich** [comment]
As far as framework selection goes [Junit](https://junit.org/junit5/) seems like the obvious choice. I personally enjoy writing tests with [Spock](https://spockframework.org/), but I don't think it's quite as mainstream.

**Comment by jgrim** [comment]
I agree Junit is the best choice. It also works well with cucumber.

**Comment by brandrich** [comment]
@jgrim I've got some basic unit tests in place for LanguageService.java and all of the utilities in the utils package. How do you feel about breaking this issue up into smaller chunks so I can start merging some unit tests into the code base?

**Comment by jgrim** [comment]
@brandrich that's a great idea! Do you want to split it up or I can if you don't want to. I just assume you'll have a better understanding on how you'd like to do it.

**Comment by brandrich** [comment]
I was thinking it would probably easiest to just split unit tests up package by package. So announcement, comment, etc. I think we spoke about this previously, but there's no reason to bother creating any sort of testing for anything in the api.lemmy.v3 package, correct?
