### ISSUE TITLE
SearchService#searchPostByUrl breaks if the number of Posts is less than a full page

### ISSUE THREAD

**Issue by alter-kaker** [sublinks/sublinks-api#424]
This method fails with a `IndexOutOfBoundsException` if the number of posts returned in the `CrossPost.posts` field is less than needed to fill the current requested page.

For example:
- 0 Post objects returned for page=0, pageSize=1
- 1 Post objects returned for page=0, pageSize=2
- 3 Post objects returned for page=1, pageSize=2
- 4 Post objects returned for page=2, pageSize=4

**Comment by alter-kaker** [comment]
See disabled tests in https://github.com/sublinks/sublinks-api/pull/423

**Comment by Pdzly** [comment]
The issue on hand here is that we expect a page range from 1-open end. I will fix it by clamping that value in the service.

And add some java doc to there when i am already there
